# Generated by Django 3.1.1 on 2020-09-26 15:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('load_capacity', models.IntegerField(blank=True, null=True, verbose_name='Грузоподъёмность (т)')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('polygon', models.TextField(blank=True, null=True, verbose_name='Полигон (WKT)')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=255, verbose_name='Бортовой номер')),
                ('truck_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.truckmodel', verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_load', models.IntegerField(blank=True, null=True, verbose_name='Текущая загрузка (т)')),
                ('current_sio2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='SiO2 (%)')),
                ('current_fe', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Fe (%)')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.truck', verbose_name='Самосвал')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.warehouse', verbose_name='Склад')),
            ],
        ),
    ]
