# Generated by Django 3.1.1 on 2020-09-26 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='current_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Текущее кол-во руды (т)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='current_fe',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Содержание Fe (%)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='current_sio2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Содержание SiO2 (%)'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='current_fe',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Содержание Fe (%)'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='current_sio2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Содержание SiO2 (%)'),
        ),
    ]
