# Generated by Django 3.1.1 on 2020-09-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200926_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='truck_model',
            new_name='model',
        ),
    ]
